name: Download Website and Build Next.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  download-and-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (for Next.js)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies (Next.js)
      - name: Install dependencies
        run: npm install

      # Step 4: Download website using wget
      - name: Download website assets
        run: |
          wget -r -l1 -H -nd -A html,css,js,jpg,png,gif,jpeg,woff,woff2,tff,eot,svg https://baysystech.com
          
      # Step 5: Build Next.js app
      - name: Build Next.js app
        run: npm run build

      # Step 6: Export static files (optional if using static export)
      - name: Export static files
        run: npm run export

      # Step 7: Upload build and exported files as artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build-artifacts
          path: |
            .next
            out  # Only if you are using static export
            public  # If you're using static assets
